// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfIX-JUVhgPRhw4m7kW3ij68YYvHgVQw0',
    appId: '1:282266138750:web:54f80e8d86b5749497402f',
    messagingSenderId: '282266138750',
    projectId: 'asthma-alert-a38f8',
    authDomain: 'asthma-alert-a38f8.firebaseapp.com',
    storageBucket: 'asthma-alert-a38f8.firebasestorage.app',
    measurementId: 'G-4E19CHBS48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUgc3s5vxPvXc9DtwlKqAvIXqXKFvvH64',
    appId: '1:282266138750:android:ac843172f2ed376497402f',
    messagingSenderId: '282266138750',
    projectId: 'asthma-alert-a38f8',
    storageBucket: 'asthma-alert-a38f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAUV4v4jy_xulqMxBQC9CLOUubOJguszA',
    appId: '1:282266138750:ios:517cc6ee5201a9d197402f',
    messagingSenderId: '282266138750',
    projectId: 'asthma-alert-a38f8',
    storageBucket: 'asthma-alert-a38f8.firebasestorage.app',
    iosBundleId: 'com.example.asthmaAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAUV4v4jy_xulqMxBQC9CLOUubOJguszA',
    appId: '1:282266138750:ios:517cc6ee5201a9d197402f',
    messagingSenderId: '282266138750',
    projectId: 'asthma-alert-a38f8',
    storageBucket: 'asthma-alert-a38f8.firebasestorage.app',
    iosBundleId: 'com.example.asthmaAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfIX-JUVhgPRhw4m7kW3ij68YYvHgVQw0',
    appId: '1:282266138750:web:a4d9eae29ac7dad897402f',
    messagingSenderId: '282266138750',
    projectId: 'asthma-alert-a38f8',
    authDomain: 'asthma-alert-a38f8.firebaseapp.com',
    storageBucket: 'asthma-alert-a38f8.firebasestorage.app',
    measurementId: 'G-ZW2CQ16RPW',
  );
}
